openapi: 3.0.0
info:
  version: 1.0.0
  title: Ulta API
  description: Ulta用のAPIイベント情報やグループの情報を取得できる。
servers:
  - url: http://localhost:10800
    description: ulta用のURLです
paths:
  /events:
    get:
      tags:
      - events
      summary: Get all ebents
      description: Return an array of Event model
      responses:
        '200':
          description: A JSON array of Event model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
                example: 
                  - id: 1
                    name: Vahul練習
                    description: vahulの練習です。みなさんどうぞ。
                    start_time: 2020-01-01T01:01
                    end_time: 2020-01-01T01:01
                  - id: 2
                    name: BeA練習
                    description: BeAの練習です。みなさんどうぞ。
                    start_time: 2020-01-01T01:01
                    end_time: 2020-01-01T01:01
    post:
      tags:
      - events
      summary: Create a new event
      description: Create a new event
      requestBody:
        description: Create a new event
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
            example:
              id: 1
              name: Vahul練習
              description: vahulの練習です。みなさんどうぞ。
              start_time: 2020-01-01T01:01
              end_time: 2020-01-01T01:01
      responses:
        '201':
          description: CREATED
  /events/{eventId}:
    get:
      tags:
      - events
      summary: Get event by event ID
      description: Return a single Event model
      parameters: 
        - name: eventId
          in: path
          description: event Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A  Event model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Event'
                example: 
                  id: 1
                  name: Vahul練習
                  description: vahulの練習です。みなさんどうぞ。
                  start_time: 2020-01-01T01:01
                  end_time: 2020-01-01T01:01
  /users/{userId}:
    get:
      tags:
      - users
      summary: Get user by user ID
      description: Return a single User model
      parameters: 
        - name: userId
          in: path
          description: user Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single User model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
                example: 
                  id: 1
                  name: 佐藤太郎
components:
  schemas:
    Event:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Vahul練習
        description:
          type: string
          example: vahulの練習です。みなさんどうぞ。
        start_time:
          type: string
          example: 2020-01-01T01:01
        end_time:
          type: string
          example: 2020-01-01T01:01
    User:
      type: object
      required: 
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 佐藤太郎
security:
  - api_key: []
tags:
  - name: events
    description: Access to Events
  - name: users
    description: Access to Users
